### ISSUE TITLE
Trainbot gave me a train in the past

### ISSUE THREAD

**Issue by zarino** [fawkesley/train-bot-uk#13]
![screen shot 2014-01-29 at 17 16 30](https://f.cloud.github.com/assets/739624/2032001/40a05570-8909-11e3-92fb-5112a964faa9.png)

**Comment by fawkesley** [comment]
Might be lack of NTP.
Also possibly should add a couple of minutes to "now" in the request.

**Comment by zarino** [comment]
If I turned on geolocation in my twitter client, could you add a delay based on how long it would take me to walk to the station ;-)

**Comment by zarino** [comment]
I'd pay for it ;-)

**Comment by fawkesley** [comment]
Regression!

```
ERROR:root:search_trains() got an unexpected keyword argument 'when'
Traceback (most recent call last):
  File "/home/paul/repo/train-times-tweeter/train_bot_uk/train_bot_uk.py", line 51, in run
    response = make_response_message(message)
  File "/home/paul/repo/train-times-tweeter/train_bot_uk/train_bot_uk.py", line 100, in make_response_message
    return parser.reply(**response_params)
  File "/home/paul/repo/train-times-tweeter/train_bot_uk/responders/journey_responder.py", line 30, in reply
    when=datetime.datetime.now() + datetime.timedelta(minutes=5))
TypeError: search_trains() got an unexpected keyword argument 'when'
```

**Comment by fawkesley** [comment]
Closed by https://github.com/paulfurley/train-bot-uk/pull/34
