### ISSUE TITLE
Falls over on Euston

### ISSUE THREAD

**Issue by fawkesley** [fawkesley/train-bot-uk#16]
```
WARNING:root:Failed to parse: ' 
                        Euston Square 



                                        Tube



        '
ERROR:root:'NoneType' object is not iterable
Traceback (most recent call last):
  File "./main.py", line 34, in run
    response = make_response_message(message)
  File "./main.py", line 97, in make_response_message
    _unescape(to))
  File "/home/paul/repo/train-times-tweeter/venv/src/uktrains/uktrains/uktrains.
py", line 94, in search_trains
    *args)
  File "/home/paul/repo/train-times-tweeter/venv/src/uktrains/uktrains/uktrains.
py", line 112, in get_trains
    journeys.append(_parse_station_from_tr(tr))
  File "/home/paul/repo/train-times-tweeter/venv/src/uktrains/uktrains/uktrains.
py", line 124, in _parse_station_from_tr
    tr.cssselect('td.to')[0].text_content())
TypeError: 'NoneType' object is not iterable
```

**Comment by fawkesley** [comment]
Need to bump version of `python-uk-trains` to 0.0.2
