### ISSUE TITLE
Discover the cause of this crash

### ISSUE THREAD

**Issue by fawkesley** [fawkesley/train-bot-uk#17]
(and it didn't recover)

```
/Dore
Traceback (most recent call last):
  File "./main.py", line 164, in <module>
    main()
  File "./main.py", line 65, in main
    stream.filter(track=[_MY_NAME])  # blocking function
  File "/home/paul/repo/train-times-tweeter/venv/local/lib/python2.7/site-packages/tweepy/streami
ng.py", line 299, in filter
    self._start(async)
  File "/home/paul/repo/train-times-tweeter/venv/local/lib/python2.7/site-packages/tweepy/streami
ng.py", line 236, in _start
    self._run()
  File "/home/paul/repo/train-times-tweeter/venv/local/lib/python2.7/site-packages/tweepy/streami
ng.py", line 173, in _run
    self._read_loop(resp)
  File "/home/paul/repo/train-times-tweeter/venv/local/lib/python2.7/site-packages/tweepy/streami
ng.py", line 214, in _read_loop
    c = resp.read(1)
  File "/usr/lib/python2.7/httplib.py", line 541, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 586, in _read_chunked
    raise IncompleteRead(''.join(value))
httplib.IncompleteRead: IncompleteRead(0 bytes read)
```

Was this a tweepy problem..?

**Comment by fawkesley** [comment]
Shouldn't have been closed, bad xref.
