### ISSUE TITLE
Error processing: `somewhere to nowhere`

### ISSUE THREAD

**Issue by fawkesley** [fawkesley/train-bot-uk#45]
Full message:

```
InboundMessage(channel='twitter', sender='paul_furley', content='somewhere to nowhere', extra={'tweet_id': 621745632101969920})
```

The error was:

```
Traceback (most recent call last):
  File "/home/paulfurley/repo/train-bot-uk/trainbot/handle_message.py", line 14, in handle_message
    reply_content = make_reply(message.content)
  File "/home/paulfurley/repo/train-bot-uk/trainbot/handle_message.py", line 39, in make_reply
    return parser.reply(**response_params)
  File "/home/paulfurley/repo/train-bot-uk/trainbot/responders/journey_responder.py", line 30, in reply
    when=datetime.datetime.now() + datetime.timedelta(minutes=5))
  File "/home/paulfurley/repo/python-uk-trains/uktrains/uktrains.py", line 92, in search_trains
    get_station(from_name),
  File "/home/paulfurley/repo/python-uk-trains/uktrains/uktrains.py", line 61, in get_station
    station = search_stations(station_name)[0]  # TODO: don't just get 1st
  File "/home/paulfurley/repo/python-uk-trains/uktrains/uktrains.py", line 74, in search_stations
    for result in json.loads(stations_json):
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by fawkesley** [comment]
Excellent! I'd call this an upvote for #12
